# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  working_directory: ~/repo
  docker:
    # specify the version you desire here
    - image: cypress/base:8

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - cache-test-{{ checksum "package.json" }}

      - run:
          name: Install app dependencies
          command: yarn install

      - run:
          name: Install and verify cypress
          command: yarn install:cypress

      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
            - ~/frameworks/cypress/.npm
            - ~/frameworks/cypress/.cache
          key: cache-test-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths:
            - repo
            - .cache/Cypress

  test:
    <<: *defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn ci
      - store_artifacts:
          path: frameworks/cypress/cypress/videos
      - store_artifacts:
          path: frameworks/cypress/cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
