version: 2.1
orbs:
  cypress: cypress-io/cypress@1.8
workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
          start: npm run start
          spec: cypress/integration/todosAapp/*